client_id = "50d82a1ec2b19da108f743c6576b3f7d"
name = "Probability App"
application_url = "https://app.probabilityia.com.co"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "probability-8291.myshopify.com"

[access_scopes]
scopes = "read_customers,read_fulfillments,read_orders,write_orders,read_products,write_products,write_customers"

[auth]
redirect_urls = [
  "https://app.probabilityia.com.co/api/v1/shopify/callback"
]

[webhooks]
api_version = "2024-10"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "https://app.probabilityia.com.co/api/v1/integrations/shopify/webhooks/compliance"
